-- MySQL Script generated by MySQL Workbench
-- 05/12/15 11:56:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fdc_as
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fdc_as
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fdc_as` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fdc_as` ;

-- -----------------------------------------------------
-- Table `fdc_as`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fdc_as`.`profiles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `middle_name` VARCHAR(50) NULL,
  `birthdate` DATETIME NULL,
  `picture` VARCHAR(100) NULL,
  `contact` VARCHAR(30) NULL,
  `facebook` VARCHAR(30) NULL,
  `email` VARCHAR(30) NULL,
  `gender` CHAR(1) NULL,
  `address` VARCHAR(120) NULL,
  `contact_person` VARCHAR(50) NULL,
  `contact_person_no` VARCHAR(30) NULL,
  `signature` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fdc_as`.`positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fdc_as`.`positions` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fdc_as`.`position_levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fdc_as`.`position_levels` (
  `id` INT(3) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(50) NULL,
  `positions_id` INT(5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_position_levels_positions1_idx` (`positions_id` ASC),
  CONSTRAINT `fk_position_levels_positions1`
    FOREIGN KEY (`positions_id`)
    REFERENCES `fdc_as`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fdc_as`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fdc_as`.`employees` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `employee_id` VARCHAR(45) NOT NULL,
  `tin` VARCHAR(20) NULL,
  `salary` VARCHAR(255) NULL,
  `profile_id` INT(11) NOT NULL,
  `drug_test` VARCHAR(20) NULL,
  `medical` VARCHAR(45) NULL,
  `pagibig` VARCHAR(30) NULL,
  `philhealth` VARCHAR(20) NULL,
  `sss` VARCHAR(20) NULL,
  `insurance_id` VARCHAR(20) NULL,
  `f_time_in` TIME NULL,
  `f_time_out` TIME NULL,
  `l_time_in` TIME NULL,
  `l_time_out` TIME NULL,
  `username` VARCHAR(30) NULL,
  `password` VARCHAR(255) NULL,
  `role` INT(2) NULL,
  `position_id` INT(5) NULL,
  `position_level_id` INT(3) NULL,
  `current_contract_id` INT(11) NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`id`, `employee_id`),
  INDEX `fk_employees_profiles_idx` (`profile_id` ASC),
  INDEX `fk_employees_positions1_idx` (`position_id` ASC),
  INDEX `fk_employees_position_levels1_idx` (`position_level_id` ASC),
  CONSTRAINT `fk_employees_profiles`
    FOREIGN KEY (`profile_id`)
    REFERENCES `fdc_as`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_positions1`
    FOREIGN KEY (`position_id`)
    REFERENCES `fdc_as`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_position_levels1`
    FOREIGN KEY (`position_level_id`)
    REFERENCES `fdc_as`.`position_levels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fdc_as`.`contract_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fdc_as`.`contract_logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(250) NULL,
  `date_start` DATETIME NULL,
  `date_end` DATETIME NULL,
  `document` VARCHAR(100) NULL,
  `salary` VARCHAR(255) NULL,
  `deminise` DECIMAL(12,2) NULL,
  `term` VARCHAR(25) NULL,
  `position` VARCHAR(50) NULL,
  `status` TINYINT NULL,
  `employees_id` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contracts_employees2_idx` (`employees_id` ASC),
  CONSTRAINT `fk_contracts_employees2`
    FOREIGN KEY (`employees_id`)
    REFERENCES `fdc_as`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fdc_as`.`attendances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fdc_as`.`attendances` (
  `id` INT(11) NOT NULL,
  `f_time_in` TIME NULL,
  `f_time_out` TIME NULL,
  `l_time_in` TIME NULL,
  `l_time_out` TIME NULL,
  `total_time` TIME NULL,
  `date` DATE NOT NULL,
  `status` TINYINT NULL,
  `employees_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attendances_employees1_idx` (`employees_id` ASC),
  CONSTRAINT `fk_attendances_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `fdc_as`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fdc_as`.`employee_offenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fdc_as`.`employee_offenses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `offense` VARCHAR(50) NULL,
  `max_offense` INT(2) NULL,
  `remarks` VARCHAR(250) NULL,
  `nature` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fdc_as`.`employee_offense_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fdc_as`.`employee_offense_logs` (
  `id` INT(11) NOT NULL,
  `date` DATETIME NULL,
  `effect` VARCHAR(100) NULL,
  `suspend_from` DATETIME NULL,
  `suspend_to` DATETIME NULL,
  `is_read` TINYINT NULL,
  `status` TINYINT NULL,
  `employees_id` VARCHAR(20) NOT NULL,
  `employee_offenses_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_offense_logs_employees1_idx` (`employees_id` ASC),
  INDEX `fk_employee_offense_logs_employee_offenses1_idx` (`employee_offenses_id` ASC),
  CONSTRAINT `fk_employee_offense_logs_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `fdc_as`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_offense_logs_employee_offenses1`
    FOREIGN KEY (`employee_offenses_id`)
    REFERENCES `fdc_as`.`employee_offenses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fdc_as`.`employee_leaves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fdc_as`.`employee_leaves` (
  `id` INT(11) NOT NULL,
  `leave` VARCHAR(45) NULL,
  `days` INT(3) NULL,
  `days_left` INT(3) NULL,
  `status` TINYINT NULL,
  `employees_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_leaves_employees1_idx` (`employees_id` ASC),
  CONSTRAINT `fk_employee_leaves_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `fdc_as`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fdc_as`.`employee_leave_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fdc_as`.`employee_leave_logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `reason` VARCHAR(250) NULL,
  `request_date` DATETIME NULL,
  `from_date` DATETIME NULL,
  `to_date` DATETIME NULL,
  `document` VARCHAR(100) NULL,
  `request_to` INT(2) NULL,
  `status` TINYINT NULL,
  `emp_leader_id` VARCHAR(20) NULL,
  `employee_id` VARCHAR(20) NOT NULL,
  `employee_leave_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_leave_logs_employees1_idx` (`employee_id` ASC),
  INDEX `fk_employee_leave_logs_employee_leaves1_idx` (`employee_leave_id` ASC),
  CONSTRAINT `fk_employee_leave_logs_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `fdc_as`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_leave_logs_employee_leaves1`
    FOREIGN KEY (`employee_leave_id`)
    REFERENCES `fdc_as`.`employee_leaves` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
